# Copyright (c) 2019-2020-2021 Luca Cappa
# Released under the term specified in file LICENSE.txt
# SPDX short identifier: MIT
#
# The peculiarity of this workflow is that assumes vcpkg stored as a submodule of this repository.
# This workflow does the following:
# - Restores vcpkg artifacts from cache.
# - Sets up vcpkg if needed. Will automatically run vcpkg to install dependencies
#   described by the vcpkg.json manifest file. It will be a no-op if those are restored from cache.

name: vcpkg

inputs:
  triplet:
    required: true
outputs: {}

runs: 
  using: "composite"
  steps:
    - name: Setup cmake
      uses: lukka/get-cmake@latest
        
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v10
      id: runvcpkg
      with:
        vcpkgJsonGlob: 'vcpkg.json'
      env:
        VCPKG_DEFAULT_TRIPLET: ${{ inputs.triplet }}
    
    - name: Print output of run-vcpkg's action.
      run: echo "root='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_DEFAULT_TRIPLET_OUT }}' "
      shell: bash
      
    - name: Run CMake (consuming CMakePreset.json and vcpkg.json by vcpkg)
      uses: lukka/run-cmake@v10
      with:
        # This is the name of the CMakePresets.json's configuration to use to generate
        # the project files. This configuration leverages the vcpkg.cmake toolchain file to
        # run vcpkg and install all dependencies specified in vcpkg.json.
        configurePreset: 'vcpkg'
      env:
        VCPKG_OVERLAY_TRIPLETS: 'custom-triplets'
    
    - name: List $RUNNER_WORKSPACE after build
      run: find $RUNNER_WORKSPACE
      shell: bash
    
    - name: Zip artifacts
      run: 7z a ${{ inputs.triplet }}.zip ./vcpkg_installed/${{ inputs.triplet }}/* -r
      shell: bash
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.triplet }}
        path: ${{ inputs.triplet }}.zip
