name: deploy
on: [workflow_dispatch]

jobs:
  windows-x64:
    - uses: ./.github/actions/vcpkg
      os: windows-latest
      triplet: x64-windows
      
  windows-x86:
    - uses: ./.github/actions/vcpkg
      os: windows-latest
      triplet: x86-windows
        
  linux-x64:
    - uses: ./.github/actions/vcpkg
      os: linux-latest
      triplet: x64-linux
        
  osx-x64:
    - uses: ./.github/actions/vcpkg
      os: osx-latest
      triplet: x64-osx
        
  pack-nuget:
    name: pack-nuget
    needs: [ windows-x64, windows-x86, linux-x64, osx-x64 ]
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      
      - name: Install .NET tools
        run: dotnet tool install --global ClangSharpPInvokeGenerator --version 13.0.0-beta1
          
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: x64-windows-include
          path: x64-windows-include.zip
          
      - name: Unzip artifacts
        run: 7z x x64-windows-include.zip -oinclude_artifacts
          
      - name: Create sources
        run: | 
          ClangSharpPInvokeGenerator --file-directory include_artifacts "@scripts/GenerateZstd.rsp"
          ClangSharpPInvokeGenerator --file-directory include_artifacts "@scripts/GenerateZdict.rsp"
      
      - name: Restore
        run: dotnet restore
      
      - name: Build
        run: dotnet build -c Release --no-restore 
        
      - name: Test
        run: dotnet test -c Release --no-restore --no-build
       
      - name: Pack
        run: dotnet pack -c Release --no-restore --no-build --verbosity normal
        
      - name: Nuget Push 
        run: dotnet nuget push artifacts/pkg/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }} --skip-duplicate
        
      