name: deploy
on: [workflow_dispatch]

env:
  VCPKG_INSTALLED_DIR: vcpkg_installed

jobs:
  vcpkg_windows-x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: ./.github/workflows/vcpkg
        with:
          triplet: x64-windows
      
  vcpkg_windows-x86:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: ./.github/workflows/vcpkg
        with:
          triplet: x86-windows

  vcpkg_linux-x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: ./.github/workflows/vcpkg
        with:
          triplet: x64-linux
      
  vcpkg_osx-x64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: ./.github/workflows/vcpkg
        with:
          triplet: x64-osx
        
  pack-nuget:
    name: pack-nuget
    needs: [ vcpkg_windows-x64, vcpkg_windows-x86, vcpkg_linux-x64, vcpkg_osx-x64 ]
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      
      - name: Install .NET tools
        run: dotnet tool install --global ClangSharpPInvokeGenerator --version 13.0.0-beta1
          
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: x64-windows-include
          path: x64-windows-include.zip
          
      - name: Unzip artifacts
        run: 7z x x64-windows-include.zip -oinclude_artifacts
          
      - name: Create sources
        run: | 
          ClangSharpPInvokeGenerator --file-directory include_artifacts "@scripts/GenerateZstd.rsp"
          ClangSharpPInvokeGenerator --file-directory include_artifacts "@scripts/GenerateZdict.rsp"
      
      - name: Restore
        run: dotnet restore
      
      - name: Build
        run: dotnet build -c Release --no-restore 
        
      - name: Test
        run: dotnet test -c Release --no-restore --no-build
       
      - name: Pack
        run: dotnet pack -c Release --no-restore --no-build --verbosity normal
        
      - name: Nuget Push 
        run: dotnet nuget push artifacts/pkg/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }} --skip-duplicate
        
      